# Generated by Django 2.2.12 on 2020-04-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200408_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_phone_pure',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats_owned',
            field=models.ManyToManyField(blank=True, related_name='flat_owner', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
